config/routes.rb
Build1::Application.routes.draw do
  resources :streams

  match "/auth/twitter/callback" => "sessions#create"
  match "/signout" => "session#destroy", :as => :signout
  
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  attr_accessible :data
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid

  def self.create_with_omniauth(auth)
  	create! do |user|
  		user.provider = auth["provider"]
  		user.uid = auth["uid"]
  		user.name = auth["info"]["name"]
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	 	auth = request.env['omniauth.auth']
	 	puts auth.to_yaml
	 	user = User.find_by_provider_and_uid(auth["provider"],auth["uid"]) || User.create_with_omniauth(auth)
	 	session[:user_id] = user.id
	 	redirect_to '/streams', :notice => "Signed In!"
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/streams', :notice => "Signed Out!"
	end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  # GET /streams
  # GET /streams.json
  def index
    @streams = Stream.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @streams }
    end
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
    @stream = Stream.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stream }
    end
  end

  # GET /streams/new
  # GET /streams/new.json
  def new
    @stream = Stream.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stream }
    end
  end

  # GET /streams/1/edit
  def edit
    @stream = Stream.find(params[:id])
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = Stream.new(params[:stream])

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'Stream was successfully created.' }
        format.json { render json: @stream, status: :created, location: @stream }
      else
        format.html { render action: "new" }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /streams/1
  # PUT /streams/1.json
  def update
    @stream = Stream.find(params[:id])

    respond_to do |format|
      if @stream.update_attributes(params[:stream])
        format.html { redirect_to @stream, notice: 'Stream was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream = Stream.find(params[:id])
    @stream.destroy

    respond_to do |format|
      format.html { redirect_to streams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Build1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div>
 	<%= link_to "Sign in with Twitter", '/auth/twitter'%>
 	Current session id is: <%= session[:user_id] %>
 </div>
 <div>
 	<%= session[:user_id] = nil %>
 	<%= link_to "Sign Out of Twitter", '/streams'%>
 </div>
<%= yield %>

</body>
</html>

app/views/streams/_form.html.erb
<%= form_for(@stream) do |f| %>
  <% if @stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stream.errors.count, "error") %> prohibited this stream from being saved:</h2>

      <ul>
      <% @stream.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/streams/edit.html.erb
<h1>Editing stream</h1>

<%= render 'form' %>

<%= link_to 'Show', @stream %> |
<%= link_to 'Back', streams_path %>

app/views/streams/index.html.erb
<h1>Listing streams</h1>

<table>
  <tr>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @streams.each do |stream| %>
  <tr>
    <td><%= stream.data %></td>
    <td><%= link_to 'Show', stream %></td>
    <td><%= link_to 'Edit', edit_stream_path(stream) %></td>
    <td><%= link_to 'Destroy', stream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stream', new_stream_path %>

app/views/streams/new.html.erb
<h1>New stream</h1>

<%= render 'form' %>

<%= link_to 'Back', streams_path %>

app/views/streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @stream.data %>
</p>


<%= link_to 'Edit', edit_stream_path(@stream) %> |
<%= link_to 'Back', streams_path %>